services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./site:/var/www/html
    depends_on:
      - db

  db:
    image: mysql
    restart: always
    volumes:
      - ./data:/lamp
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 101010

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8082:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - db

  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"

  ssh-agent:
    image: jenkins/ssh-agent
    environment:
      JENKINS_AGENT_SSH_PUBKEY: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAr..."
  
volumes:
  db:
  jenkins_home: