pipeline {
    agent any

   stages {
        stage('Checkout') {
            steps {
                
                git 'https://github.com/khaledsalahat/linux.git '
            }
        }

        stage('Build') {
            steps {
                
                sh 'docker compose build'
            }
        }

        stage('Deploy') {
            steps {
                
                sh 'docker compose up -d'
            }
        }
    }

    post {
        success {
            echo 'Build and deployment successful!'
        }
        failure {
            echo 'Build or deployment failed!'
        }
    }
}
